package by.epam.javatraining.webproject.util;

public class Parameters {

    public static final String USER = "user";
    public static final String USER_ID = "user_id";
    public static final String CARD = "card";
    public static final String CARD_ID = "card_id";
    public static final String DOCTOR_ID = "doctor_id";
    public static final String LOGIN = "login";
    public static final String PASSWORD = "password";
    public static final String OLD_PASSWORD = "old_password";
    public static final String NEW_PASSWORD = "new_password";
    public static final String LOGIN_ERROR = "loginError";
    public static final String PASSWORD_ERROR = "passwordError";
    public static final String ERROR = "error";
    public static final String ROLES = "roles";
    public static final String SEX = "sex";
    public static final String DATE = "date";
    public static final String DISCHARGE_DATE = "discharge_date";
    public static final String ADMISSION_DATE = "admission_date";
    public static final String BIRTH_DATE = "birth_date";
    public static final String ROLE = "role";
    public static final String FINAL_DIAGNOSIS = "final_diagnosis";
    public static final String DIAGNOSES = "diagnoses";
    public static final String COMPLAINTS = "complaints";
    public static final String LAST_CASE = "last_case";
    public static final String PATIENT = "patient";
    public static final String PATIENT_NAME = "patient_name";
    public static final String NAME = "name";
    public static final String SURNAME = "surname";
    public static final String PATRONYMIC = "patronymic";
    public static final String REPEAT_PASSWORD = "repeat_password";
    public static final String REPEAT_NEW_PASSWORD = "repeat_new_password";
    public static final String USERS = "users";
    public static final String DATE_PATTERN = "yyyy-MM-dd";
    public static final String COMMAND = "command";
    public static final String DETAILS = "details";
    public static final String TYPE = "type";
    public static final String LAST_CASE_ID = "last_case_id";
    public static final String TYPES = "types";
    public static final String MEDICAL_CARD = "medical_card";
    public static final String PRESCRIPTIONS = "prescriptions";
    public static final String MESSAGE = "message";
    public static final String PATIENTS = "patients";
    public static final String CASES = "cases";
    public static final String CARDS = "cards";
    public static final String AMOUNT = "amount";
    public static final String DOCTORS = "doctors";
    public static final String DOCTOR_NAMES = "doctor_names";
    public static final String CASE_ID = "case_id";
    public static final String DIAGNOSIS = "diagnosis";
    public static final String ACTIVE = "active";
    public static final String CASE = "current_case";
    public static final String ERRORS = "errors";
}
